### PR TITLE
fix: bug fix of adding same task again

### LINKED ISSUE #33: Bug in adding task
User is able to add same todo task again instead there should be a display of message like "you have already added that task" or something like that and that task should not be added 

Current Behavior--
image

While it should not allow this thing and display a warning like message

Also the "Tasks" heading should remain hide until there are no tasks added I want to remove these 2 bugs

### PR DESCRIPTION
**Pull request by GbCderr14**
Same Task issue resolved : 
image

Resolves #33

### CODE REVIEW

File: assets/to-do-task/loadTask.js [hunk 1]
```diff
@@ -3,6 +3,9 @@ const list_el = document.querySelector("#tasks");
 
 if (localStorage.getItem("to-do-task") != null) {
   var task_list = JSON.parse(localStorage.getItem("to-do-task"));
+  const heading = document.createElement("h2");
+  heading.innerText = "TASKS";
```
Comment (malivinayak) [inline assets/to-do-task/loadTask.js:7]: Switch from uppercase to CamelCase:

Replace `TASKS` with `Tasks`.

**Review by malivinayak — CHANGES_REQUESTED** [review]

**Review by malivinayak — APPROVED** [review]
LGTM!

File: assets/to-do-task/loadTask.js (hunk 1 above)
Comment (malivinayak) [reply assets/to-do-task/loadTask.js]: Done at e55c9933a448bf2dd8b156224737b0747921bf07

**Comment by malivinayak** [comment]
@GbCderr14 Thank You for your contribution

You can also contribute in following:
1. https://github.com/malivinayak/Markdown
1. https://github.com/malivinayak/Tic-Tac-Toe
1. https://github.com/malivinayak/Rock-Paper-Scissors
1. https://github.com/malivinayak/Alarm-Clock
1. https://github.com/malivinayak/world-map
